// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic type structure
// Run `npx supabase gen types typescript --project-id YOUR_PROJECT_ID` to generate

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          display_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      bands: {
        Row: {
          id: string
          name: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      band_members: {
        Row: {
          id: string
          band_id: string
          profile_id: string
          role: string
          joined_at: string
        }
        Insert: {
          id?: string
          band_id: string
          profile_id: string
          role: string
          joined_at?: string
        }
        Update: {
          id?: string
          band_id?: string
          profile_id?: string
          role?: string
          joined_at?: string
        }
      }
      venues: {
        Row: {
          id: string
          name: string
          address: string
          city: string
          state: string | null
          country: string
          latitude: number | null
          longitude: number | null
          place_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          address: string
          city: string
          state?: string | null
          country: string
          latitude?: number | null
          longitude?: number | null
          place_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string
          city?: string
          state?: string | null
          country?: string
          latitude?: number | null
          longitude?: number | null
          place_id?: string | null
          created_at?: string
        }
      }
      shows: {
        Row: {
          id: string
          band_id: string
          venue_id: string
          date: string
          time: string | null
          status: string
          notes: string | null
          setlist_name: string | null
          weather_summary: string | null
          weather_temp: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          band_id: string
          venue_id: string
          date: string
          time?: string | null
          status?: string
          notes?: string | null
          setlist_name?: string | null
          weather_summary?: string | null
          weather_temp?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          band_id?: string
          venue_id?: string
          date?: string
          time?: string | null
          status?: string
          notes?: string | null
          setlist_name?: string | null
          weather_summary?: string | null
          weather_temp?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      earnings: {
        Row: {
          id: string
          show_id: string
          amount: number
          currency: string
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          show_id: string
          amount: number
          currency?: string
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          show_id?: string
          amount?: number
          currency?: string
          description?: string | null
          created_at?: string
        }
      }
      assistant_plans: {
        Row: {
          id: string
          band_id: string
          profile_id: string
          user_input: string
          plan_description: string
          actions: any
          status: string
          created_at: string
          applied_at: string | null
        }
        Insert: {
          id?: string
          band_id: string
          profile_id: string
          user_input: string
          plan_description: string
          actions: any
          status?: string
          created_at?: string
          applied_at?: string | null
        }
        Update: {
          id?: string
          band_id?: string
          profile_id?: string
          user_input?: string
          plan_description?: string
          actions?: any
          status?: string
          created_at?: string
          applied_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}